name = "DemoPackageEB"
uuid = "f6b4e82c-dda5-44a1-ac0b-eb610e1931ab"
authors = ["Eleonora Bano <eleonora.bano@outlook.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
